;;all the require are here!
(require 'midnight)
(require 'ido)
(require 'yasnippet)
(require 'multi-term)
(require 'zenburn-theme)
(require 'emmet-mode)
(require 'magit)
(require 'uniquify)
(require 'uniquify)
(require 'expand-region)
(require 'php-auto-yasnippets)
(require 'web-mode)
(require 'moz)
(require 'smex)
